version: 0.2

env:
  variables:
    MIN_SDK_VERSION: "24"

  secrets-manager:
    APP_VERSION: "apps/InfinityForRedditBuilder:AppVersion"
    REDDIT_USERNAME: "apps/InfinityForRedditBuilder:RedditUsername"
    REDDIT_CLIENT_ID: "apps/InfinityForRedditBuilder:RedditApiKey"
    KEYSTORE_PATH: "apps/InfinityForRedditBuilder:KeystorePath"
    KEYSTORE_PASSWORD: "apps/InfinityForRedditBuilder:KeystorePassword"
  

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      java: corretto21
      python: 3.12
    commands:
      - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
      - unzip -q android-sdk.zip -d android-sdk
      - export ANDROID_SDK_ROOT=$CODEBUILD_SRC_DIR/android-sdk
      - yes | $CODEBUILD_SRC_DIR/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platforms;android-34" "build-tools;34.0.0"
      - export PATH=$PATH:$CODEBUILD_SRC_DIR/android-sdk/tools/bin:$CODEBUILD_SRC_DIR/android-sdk/platform-tools:$CODEBUILD_SRC_DIR/android-sdk/build-tools/34.0.0

  pre_build:
    on-failure: ABORT
    commands:
      # Download and extract Infinity-For-Reddit source zip
      - wget --quiet --output-document=Infinity-For-Reddit.zip "https://github.com/Docile-Alligator/Infinity-For-Reddit/archive/refs/tags/$APP_VERSION.zip"
      - unzip -q "Infinity-For-Reddit.zip"
      - mv -T Infinity-For-Reddit-* Infinity-For-Reddit

      # Download keystore file
      - aws s3 cp $KEYSTORE_PATH infinity-for-reddit.jks

      # Run script to prepare for build
      - python3 scripts/update_build_properties.py --src-path $CODEBUILD_SRC_DIR --min-sdk $MIN_SDK_VERSION --client-id $REDDIT_CLIENT_ID --username $REDDIT_USERNAME --keystore-password KEYSTORE_PASSWORD

  build:
    on-failure: ABORT
    commands:
      - cd Infinity-For-Reddit && ./gradlew updateLintBaseline
      - cd Infinity-For-Reddit && ./gradlew assembleRelease
      - mv Infinity-For-Reddit/app/build/outputs/apk/release/app-release.apk Infinity-For-Reddit/app/build/outputs/apk/release/Infinity-For-Reddit.apk

  # post_build:
  #   on-failure: ABORT
  #   commands:
  #     # sign apk
  #     - rm infinity-for-reddit.jks
  #     - Infinity-For-Reddit/app/src/main/java/ml/docilealligator/infinityforreddit/utils/APIUtils.java

artifacts:
    files:
      - Infinity-For-Reddit/app/build.gradle
      - Infinity-For-Reddit/app/src/main/java/ml/docilealligator/infinityforreddit/utils/APIUtils.java
      - Infinity-For-Reddit/app/build/outputs/apk/release/Infinity-For-Reddit.apk
