version: 0.2

env:
  variables:
    MIN_SDK_VERSION: "24"

  secrets-manager:
    APP_VERSION: "apps/InfinityForRedditBuilder:AppVersion"
    REDDIT_USERNAME: "apps/InfinityForRedditBuilder:RedditUsername"
    REDDIT_CLIENT_ID: "apps/InfinityForRedditBuilder:RedditApiKey"
    KEYSTORE_PASSWORD: "apps/InfinityForRedditBuilder:KeystorePassword"
  

phases:
  install:
    on-failure: ABORT
    runtime-versions:
    #  java: corretto21
      python: 3.12
    # commands:
      # - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
      # - unzip -q android-sdk.zip -d android-sdk
      # - export ANDROID_SDK_ROOT=$CODEBUILD_SRC_DIR/android-sdk
      # - yes | $CODEBUILD_SRC_DIR/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platforms;android-34" "build-tools;34.0.0"
      # - export PATH=$PATH:$CODEBUILD_SRC_DIR/android-sdk/tools/bin:$CODEBUILD_SRC_DIR/android-sdk/platform-tools:$CODEBUILD_SRC_DIR/android-sdk/build-tools/34.0.0

  pre_build:
    on-failure: ABORT
    commands:
      - wget --quiet --output-document=Infinity-For-Reddit.zip "https://github.com/Docile-Alligator/Infinity-For-Reddit/archive/refs/tags/$APP_VERSION.zip"
      - unzip -q "Infinity-For-Reddit.zip"
      - mv -T Infinity-For-Reddit-* Infinity-For-Reddit
      - aws s3 cp s3://mdinicola-files/infinity-for-reddit/infinity-for-reddit.jks infinity-for-reddit.jks
      - python3 scripts/update_build_properties.py --src-path $CODEBUILD_SRC_DIR --min-sdk $MIN_SDK_VERSION --client-id $REDDIT_CLIENT_ID --username $REDDIT_USERNAME --keystore-password KEYSTORE_PASSWORD
      # - sed -i "s/minSdk 21/minSdk $MIN_SDK_VERSION/g" Infinity-For-Reddit/app/build.gradle
      # - sed -i "s/NOe2iKrPPzwscA/$REDDIT_API_KEY/g" Infinity-For-Reddit/app/src/main/java/ml/docilealligator/infinityforreddit/utils/APIUtils.java
      # - sed -i "s/infinity:\/\/localhost/http:\/\/127.0.0.1/g" Infinity-For-Reddit/app/src/main/java/ml/docilealligator/infinityforreddit/utils/APIUtils.java
      # - sed -i "s/android:ml.docilealligator.infinityforreddit:\" + BuildConfig.VERSION_NAME + \" (by \/u\/Hostilenemy)/android:personal-app:0.0.1 (by \/u\/$REDDIT_USERNAME)/g" Infinity-For-Reddit/app/src/main/java/ml/docilealligator/infinityforreddit/utils/APIUtils.java
      # Download keystore from S3

  build:
    on-failure: ABORT
    commands:
      - echo $ANDROID_SDK_ROOT
      - echo $JAVA_HOME
      - echo $PATH

  # post_build:
  #   on-failure: ABORT
  #   commands:
      # sign apk
      # remove keystore
      # remove APIUtils file

artifacts:
    files:
      - Infinity-For-Reddit/app/build.gradle
      - Infinity-For-Reddit/app/src/main/java/ml/docilealligator/infinityforreddit/utils/APIUtils.java
      - infinity-for-reddit.jks
